name: pokemonrevolution
version: '0.0.1'
type: app
base: core18

# Snapcraft metadata
title: Pokemon Revolution Online
summary: Pokemon Revolution is an online free to play Pokemon MMO
description: |
  PRO is a Pokemon MMO built from the ground up to revolutionize the way
  pokemon is played online. Enter  the massive world of Pokemon with many
  regions, both original and custom, never seen in any other game.
contact: joffreybvn@gmail.com
source-code: https://github.com/joffreybvn/pokemonrevolution-snap
issues: https://github.com/Joffreybvn/pokemonrevolution-snap/issues
website: https://pokemonrevolution.net
icon: snap/gui/logo.png
license: MIT

# Container parameters
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: all

# Application
apps:
  pokemonrevolution:
    command: ./PROClient.x86_64


parts:
  pbo-client:
    plugin: dump
    source: ./sources/zip
    source-type: local
    override-build: |
      snapcraftctl build
      chmod +x ./PROClient.x86_64
