name: pokemonrevolution
version: '0.0.3'
type: app
base: core18

# Snapcraft metadata
title: Pokemon Revolution Online
summary: Pokemon Revolution is an online free to play Pokemon MMO
description: |
  PRO is a Pokemon MMO built from the ground up to revolutionize the way
  pokemon is played online. Enter  the massive world of Pokemon with many
  regions, both original and custom, never seen in any other game.
contact: joffreybvn@gmail.com
source-code: https://github.com/joffreybvn/pokemonrevolution-snap
issues: https://github.com/Joffreybvn/pokemonrevolution-snap/issues
website: https://pokemonrevolution.net
icon: snap/gui/logo.png
license: MIT

# Container parameters
grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64

# Application
apps:
  pokemonrevolution:
    command: bin/desktop-launch $SNAP/PROClient.x86_64
    plugs:
      - network
      - x11
      - audio-playback
      - hardware-observe
      - system-observe
      - personal-files
      - opengl
      - screen-inhibit-control
      - unity7
      - wayland

parts:
  pbo-client:
    plugin: dump
    source: ./sources/zip
    source-type: local
    override-build: |
      snapcraftctl build
      chmod +x ./PROClient.x86_64
    stage-packages:
      - libglu1-mesa
    after:
      - desktop-glib-only

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
